version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2025 Funkeleinhorn <git@funkeleinhorn.com>"
SPDX-License-Identifier = "CERN-OHL-S-2.0"

[[annotations]]
path = ["custom_libraries/MOUDLE-SEEEDUINO-XIAO-ESP32C3.kicad_sym", "custom_libraries/xiao ESP32C3_PCB.pretty/*"]
SPDX-FileCopyrightText = "2025 Seeed Studio, Inc"
SPDX-License-Identifier = "MIT"
