# SPDX-FileCopyrightText: 2025 Funkeleinhorn <git@funkeleinhorn.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[toolchain]
channel    = "nightly"
components = ["rust-src", "rust-analyzer"]
targets = ["riscv32imc-unknown-none-elf"]
